---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Магазин будет SPA-приложение, которое не перезагружает страницу
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Корзина будет хранится в сессии браузера
implicit:
  - При выборе языка названия и описания товаров должны также меняться
  - В зависимости от языка должна меняться валюта (Русский - рубли, английский - доллары)
  - Список производителей должен быть доступен сразу полный, а не зависеть от страницы товаров, чтобы пользователь мог сразу выбрать необходимое
  - В корзине не нужно писать сколько штук товара осталось в магазине
